# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_CLANG_VERSION17.0.6CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019:
        CONFIG: win_64_CLANG_VERSION17.0.6CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
      win_64_CLANG_VERSION17.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022:
        CONFIG: win_64_CLANG_VERSION17.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022
=======
      ? win_64_CLANG_VERSION16.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
      : CONFIG: win_64_CLANG_VERSION16.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
>>>>>>> upstream/main
        UPLOAD_PACKAGES: 'True'
      win_64_CLANG_VERSION18.1.8CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019:
        CONFIG: win_64_CLANG_VERSION18.1.8CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
      win_64_CLANG_VERSION18.1.8CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022:
        CONFIG: win_64_CLANG_VERSION18.1.8CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022
=======
      ? win_64_CLANG_VERSION17.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
      : CONFIG: win_64_CLANG_VERSION17.0.6CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
>>>>>>> upstream/main
        UPLOAD_PACKAGES: 'True'
      win_64_CLANG_VERSION19.1CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019:
        CONFIG: win_64_CLANG_VERSION19.1CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019
        UPLOAD_PACKAGES: 'True'
<<<<<<< HEAD
      win_64_CLANG_VERSION19.1CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022:
        CONFIG: win_64_CLANG_VERSION19.1CL_VERSION19.41.34120RUNTIME_VERSION14.40.33810VCVER14.3VSYEAR2022
=======
      ? win_64_CLANG_VERSION18.1.8CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
      : CONFIG: win_64_CLANG_VERSION18.1.8CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_main
        UPLOAD_PACKAGES: 'True'
      ? win_64_CLANG_VERSION19.1.0.rc2CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019channel_targetsconda-forge_llvm_rc
      : CONFIG: win_64_CLANG_VERSION19.1.0.rc2CL_VERSION19.29.30139RUNTIME_VERSION14.29.30139VCVER14.2VSYEAR2019channel_targetsconda-forge_llvm_rc
        UPLOAD_PACKAGES: 'True'
      ? win_64_CLANG_VERSION19.1.0.rc2CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_llvm_rc
      : CONFIG: win_64_CLANG_VERSION19.1.0.rc2CL_VERSION19.41.34120RUNTIME_VERSION14.41.34120VCVER14.3VSYEAR2022channel_targetsconda-forge_llvm_rc
>>>>>>> upstream/main
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:

    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)